default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  host: db
  username: postgres
  password:
  timeout: 5000
  port: 5432

development:
  <<: *default
  database: rip_aim_development

test:
  <<: *default
  database: rip_aim_test

qa:
  <<: *default
  database: rip_aim_qa

production:
  <<: *default
  database: rip_aim_production